In [1]:
import env
from config import get_config
import numpy as np
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [2]:
env_name = "MyHalfCheetah-v2"
env_str = "half_cheetah"
cfg = get_config(env_str)
env = cfg.exp_cfg.env

O = np.load('save/expert_demonstrations/%s/obs.npy' % env_str)
A = np.load('save/expert_demonstrations/%s/act.npy' % env_str)
print(O.shape, A.shape)
print(O.min(), O.max(), O.mean(), O.std())
print(A.min(), A.max(), A.mean(), A.std())
"""
State-Space (name/joint/parameter):
- rootx     slider      position (m)
- rootz     slider      position (m)
- rooty     hinge       angle (rad)
- bthigh    hinge       angle (rad)
- bshin     hinge       angle (rad)
- bfoot     hinge       angle (rad)
- fthigh    hinge       angle (rad)
- fshin     hinge       angle (rad)
- ffoot     hinge       angle (rad)
- rootx     slider      velocity (m/s)
- rootz     slider      velocity (m/s)
- rooty     hinge       angular velocity (rad/s)
- bthigh    hinge       angular velocity (rad/s)
- bshin     hinge       angular velocity (rad/s)
- bfoot     hinge       angular velocity (rad/s)
- fthigh    hinge       angular velocity (rad/s)
- fshin     hinge       angular velocity (rad/s)
- ffoot     hinge       angular velocity (rad/s)
"""
print(O[0, 200])

(20, 251, 18) (20, 250, 6)
-23.89367979825488 893.6810099937367 29.436127083571414 101.33965305942476
-1.0 1.0 0.05576187383986439 0.7981391264502806
[554.594   0.349 415.918  -0.043   0.018   0.216  -0.704   0.458   0.604
  23.34   -0.079  10.605  -6.137  -0.828  -0.941  13.54    5.892  11.392]


In [3]:
env_name = "MySwimmer-v2"
env_str = "swimmer"
cfg = get_config(env_str)
env = cfg.exp_cfg.env

O = np.load('save/expert_demonstrations/%s/obs.npy' % env_name)
A = np.load('save/expert_demonstrations/%s/act.npy' % env_name)
print(O.shape, A.shape)
print(O.min(), O.max(), O.mean(), O.std())
print(A.min(), A.max(), A.mean(), A.std())
print(O[0, 100])

(10, 112, 10) (10, 111, 2)
-5.977867925604655 9.726793612191898 0.4648059201985191 2.366158531725691
-1.0 1.0 -0.0022904544834106318 0.8002182222025644
[ 7.238 -4.088  0.118 -0.04  -1.544  0.441  1.809 -2.097  2.956  1.551]


In [4]:
env_name = "MyCartpole-v0"
env_str = "swimmer"
cfg = get_config(env_str)
env = cfg.exp_cfg.env

O = np.load('save/expert_demonstrations/%s/obs.npy' % env_str)
A = np.load('save/expert_demonstrations/%s/act.npy' % env_str)
print(O.shape, A.shape)
print(O.min(), O.max(), O.mean(), O.std())
print(A.min(), A.max(), A.mean(), A.std())
print(O[0, 30])

(10, 112, 10) (10, 111, 2)
-5.977867925604655 9.726793612191898 0.4648059201985191 2.366158531725691
-1.0 1.0 -0.0022904544834106318 0.8002182222025644
[ 2.997 -0.566 -1.607  1.143  0.445 -0.547 -0.42   0.845 -1.709  1.413]


In [23]:
import gym

env_name = "MyPusher-v2"
env = gym.make(env_name)
print(env.observation_space, env.action_space)
print(env.reset())
print()
print(env.goal_pos)
print(env.get_body_com('tips_arm')) # 14:17
print(env.get_body_com("object"))   # 17:20
print(env.get_body_com('goal'))     # 20:23
print()
for _ in range(20):
    obs, _, _, _ = env.step(env.action_space.sample())
print(obs)

Box(23,) Box(7,)
[ 0.     0.     0.     0.     0.     0.     0.    -0.002  0.     0.005
  0.003 -0.002 -0.003  0.003  0.821 -0.6    0.     0.409 -0.223 -0.275
  0.45  -0.05  -0.323]

[0 0]
[ 0.821 -0.6    0.   ]
[ 0.409 -0.223 -0.275]
[ 0.45  -0.05  -0.323]

[ 0.066  0.239 -0.428 -2.079  1.043  0.001  1.106  0.273 -0.316 -2.066
 -0.743 -0.153 -0.036 -2.752  0.393 -0.463  0.192  0.409 -0.223 -0.275
  0.45  -0.05  -0.323]
