In [28]:
import torch

x = torch.arange(6).view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [6]:
x.repeat(2, 1)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [3]:
x.unsqueeze(1).expand(-1, 2, -1).contiguous().view(4, 3)

tensor([[0, 1, 2],
        [0, 1, 2],
        [3, 4, 5],
        [3, 4, 5]])

In [8]:
from dm_control import suite
import numpy as np

env = suite.load(domain_name="cartpole", task_name="swingup")
spec = env.action_spec()
spec

BoundedArraySpec(shape=(1,), dtype=dtype('float64'), name=None, minimum=[-1.], maximum=[1.])

In [29]:
time_step = env.reset()
print(time_step.observation)
print(time_step.observation['position'])
print(time_step.observation['velocity'])

OrderedDict([('position', array([ 0.00986964, -0.99994013, -0.01094207])), ('velocity', array([0.01310164, 0.01951717]))])
[ 0.00986964 -0.99994013 -0.01094207]
[0.01310164 0.01951717]


In [36]:
action = np.random.uniform(spec.minimum, spec.maximum, spec.shape)
env._task.get_reward(env._physics)

0.08549384155498445

In [39]:
env._task.get_observation(env._physics)

OrderedDict([('position', array([ 1.4631864 , -0.73413682, -0.67900156])),
             ('velocity', array([-0.4363628 , -0.15847509]))])

In [90]:
env._task.before_step(action, env._physics)
env._physics.step()
env._task.after_step(env._physics)
env._task.get_observation(env._physics)

OrderedDict([('position', array([ 1.80531322, -0.46391838,  0.88587795])),
             ('velocity', array([-0.03001947, -1.68065862]))])

In [99]:
from pprint import pprint

pprint(vars(env._physics))

{'_contexts': Contexts(gl=<dm_control._render.pyopengl.egl_renderer.EGLContext object at 0x7fafda937fd0>, mujoco=<dm_control.mujoco.wrapper.core.MjrContext object at 0x7fafda937f98>),
 '_data': <dm_control.mujoco.wrapper.core.MjData object at 0x7fafda9968d0>,
 '_named': NamedIndexStructs(model=<dm_control.mujoco.index.make_struct_indexer.<locals>.StructIndexer object at 0x7faff4066e90>, data=<dm_control.mujoco.index.make_struct_indexer.<locals>.StructIndexer object at 0x7fafdaa7c310>),
 '_new_warnings': array([False, False, False, False, False, False, False, False]),
 '_warnings': array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 '_warnings_before': array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)}


In [30]:
while not time_step.last():
    action = np.random.uniform(spec.minimum, spec.maximum, spec.shape)
    time_step = env.step(action)