In [1]:
import env
import gym

In [2]:
env = gym.make("MyHalfCheetah-v0")
env.observation_space, env.action_space

/home/theophile/anaconda3/envs/handful-of-trials-pytorch/lib/python3.6/site-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


(Box(18,), Box(6,))

In [3]:
env = gym.make("MyHalfCheetah-v0")
env.seed(0)
env.reset()

array([ 0.        ,  0.09307819,  0.02653819, -0.04199653, -0.07950315,
        0.03461527, -0.02148465,  0.03396921, -0.08803221, -0.0572751 ,
        0.00336234, -0.00317337,  0.04092179,  0.05138554,  0.01490225,
       -0.04298223,  0.18408469, -0.00426755])

In [4]:
env = gym.make("MyHalfCheetah-v0")
acts = [env.action_space.sample() for _ in range(1000)]

In [5]:
env = gym.make("MyHalfCheetah-v0")
env.seed(0)
env.reset()

array([ 0.        ,  0.09307819,  0.02653819, -0.04199653, -0.07950315,
        0.03461527, -0.02148465,  0.03396921, -0.08803221, -0.0572751 ,
        0.00336234, -0.00317337,  0.04092179,  0.05138554,  0.01490225,
       -0.04298223,  0.18408469, -0.00426755])

In [6]:
import copy
import numpy as np

env = copy.deepcopy(env)
obs1 = [env.step(a)[0] for a in acts]

env = copy.deepcopy(env)
obs2 = [env.step(a)[0] for a in acts]

(np.array(obs1) == np.array(obs2)).mean()

1.0

In [7]:
import numpy as np
import torch

x = np.arange(12)
x.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
x = np.arange(12)
y = torch.from_numpy(x)
y.view(2, 2, 3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [13]:
env = gym.make("MyHalfCheetah-v0")
env.unwrapped.get_action_meanings()

AttributeError: 'HalfCheetahEnv' object has no attribute 'get_action_meanings'